name: Pipeline CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Cache Nextflow
        uses: actions/cache@v4
        with:
          path: ~/.nextflow
          key: ${{ runner.os }}-nextflow-${{ hashFiles('**/nextflow.config') }}
          restore-keys: |
            ${{ runner.os }}-nextflow-

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -f bioinformatics-portfolio/pipelines/variant_calling/Dockerfile.complete -t variant-pipeline:1.0 bioinformatics-portfolio/pipelines/variant_calling

      - name: Run pipeline with test data
        run: |
          cd bioinformatics-portfolio/pipelines/variant_calling
          nextflow run main.nf -profile test,aws -with-trace -with-timeline -with-dag
          nextflow clean -f

      - name: Upload pipeline reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pipeline-reports
          path: |
            bioinformatics-portfolio/pipelines/variant_calling/trace.txt
            bioinformatics-portfolio/pipelines/variant_calling/timeline.html
            bioinformatics-portfolio/pipelines/variant_calling/pipeline_dag.html
          retention-days: 7 